# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "scraping_stock_data"
username = "root"
password = "Sorakawa.101"


MYSQL_USER = 'root'
MYSQL_HOST = 'localhost'
MYSQL_PASSWORD = 'Sorakawa.101'


